title:              "Simpliying Complexity"
email:              joluistello@gmail.com
description:        "Written by Jose Luis Tello"
author:             "Jose Luis Tello"
baseurl:            ""
url:                "https://joseluistello.github.io"

# Social Profiles
twitter_username:   
github_username: 
facebook_username:  
instagram_username:  
linkedin_username: 

# Add your google-analytics ID here to activate google analytics
google_analytics:   G-BXNJ3KME4Y # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
highlighter: rouge